/**
 * HeySure AI - 主题配置模块
 * 提供预设主题和主题管理功能：
 * - 预设主题定义（默认、深色、彩色等）
 * - 主题类型和配置结构
 * - 主题切换和预览功能
 * - 主题颜色生成
 */
import { ThemeConfig } from '@/types/theme';

// 预设主题
export const presetThemes: Record<string, ThemeConfig> = {
  default: {
    id: 'default',
    name: '默认主题',
    backgroundColor: '#ffffff',
    gridColor: '#e5e7eb',
    gridEnabled: false,
    connectionColor: '#94a3b8',
    lineColor: '#3b82f6',
    connectionWidth: 2,
    connectionStyle: 'curve',
    nodeBackgroundColor: '#f8fafc',
    nodeBorderColor: '#cbd5e1',
    nodeBorderWidth: 1,
    nodeBorderRadius: 8,
    rootNodeColor: '#3b82f6',
    textColor: '#1e293b',
    rootTextColor: '#ffffff',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    fontSize: 14,
    rootFontSize: 16,
    lineHeight: 1.5,
    shadowEnabled: true,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowBlur: 4,
    shadowOffsetX: 2,
    shadowOffsetY: 2
  },
  dark: {
    id: 'dark',
    name: '暗黑主题',
    backgroundColor: '#1e1e2e',
    gridColor: '#313244',
    gridEnabled: true,
    connectionColor: '#6c7086',
    lineColor: '#89b4fa',
    connectionWidth: 2,
    connectionStyle: 'curve',
    nodeBackgroundColor: '#313244',
    nodeBorderColor: '#45475a',
    nodeBorderWidth: 1,
    nodeBorderRadius: 8,
    rootNodeColor: '#000000ff',
    textColor: '#cdd6f4',
    rootTextColor: '#1e1e2e',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    fontSize: 14,
    rootFontSize: 16,
    lineHeight: 1.5,
    shadowEnabled: true,
    shadowColor: 'rgba(0, 0, 0, 0.3)',
    shadowBlur: 8,
    shadowOffsetX: 4,
    shadowOffsetY: 4
  },
  nature: {
    id: 'nature',
    name: '自然主题',
    backgroundColor: '#f0fdf4',
    gridColor: '#bbf7d0',
    gridEnabled: true,
    connectionColor: '#22c55e',
    lineColor: '#22c55e',
    connectionWidth: 3,
    connectionStyle: 'polyline',
    nodeBackgroundColor: '#ffffff',
    nodeBorderColor: '#86efac',
    nodeBorderWidth: 2,
    nodeBorderRadius: 12,
    rootNodeColor: '#72ffa4ff',
    textColor: '#14532d',
    rootTextColor: '#ffffff',
    fontFamily: 'Georgia, serif',
    fontSize: 14,
    rootFontSize: 18,
    lineHeight: 1.6,
    shadowEnabled: true,
    shadowColor: 'rgba(34, 197, 94, 0.2)',
    shadowBlur: 6,
    shadowOffsetX: 3,
    shadowOffsetY: 3
  },
  ocean: {
    id: 'ocean',
    name: '海洋主题',
    backgroundColor: '#0c4a6e',
    gridColor: '#0369a1',
    gridEnabled: true,
    connectionColor: '#38bdf8',
    lineColor: '#0ea5e9',
    connectionWidth: 2,
    connectionStyle: 'curve',
    nodeBackgroundColor: '#0ea5e9',
    nodeBorderColor: '#7dd3fc',
    nodeBorderWidth: 2,
    nodeBorderRadius: 20,
    rootNodeColor: '#27b4f1ff',
    textColor: '#f0f9ff',
    rootTextColor: '#0369a1',
    fontFamily: 'Trebuchet MS, sans-serif',
    fontSize: 13,
    rootFontSize: 16,
    lineHeight: 1.5,
    shadowEnabled: true,
    shadowColor: 'rgba(14, 165, 233, 0.4)',
    shadowBlur: 10,
    shadowOffsetX: 5,
    shadowOffsetY: 5
  },
  sunset: {
    id: 'sunset',
    name: '日落主题',
    backgroundColor: '#fff7ed',
    gridColor: '#fed7aa',
    gridEnabled: false,
    connectionColor: '#f97316',
    lineColor: '#f97316',
    connectionWidth: 3,
    connectionStyle: 'straight',
    nodeBackgroundColor: '#ffedd5',
    nodeBorderColor: '#fb923c',
    nodeBorderWidth: 2,
    nodeBorderRadius: 4,
    rootNodeColor: '#ea580c',
    textColor: '#431407',
    rootTextColor: '#ffffff',
    fontFamily: 'Verdana, sans-serif',
    fontSize: 14,
    rootFontSize: 17,
    lineHeight: 1.5,
    shadowEnabled: true,
    shadowColor: 'rgba(249, 115, 22, 0.25)',
    shadowBlur: 5,
    shadowOffsetX: 2,
    shadowOffsetY: 2
  },
  galaxy: {
    id: 'galaxy',
    name: '星系主题',
    backgroundColor: '#0f0f23',
    gridColor: '#1e1e3f',
    gridEnabled: true,
    connectionColor: '#a855f7',
    lineColor: '#a855f7',
    connectionWidth: 1.5,
    connectionStyle: 'curve',
    nodeBackgroundColor: '#1e1e3f',
    nodeBorderColor: '#c084fc',
    nodeBorderWidth: 1,
    nodeBorderRadius: 50,
    rootNodeColor: '#6a00ffff',
    textColor: '#f3e8ff',
    rootTextColor: '#0f0f23',
    fontFamily: 'Courier New, monospace',
    fontSize: 12,
    rootFontSize: 14,
    lineHeight: 1.4,
    shadowEnabled: true,
    shadowColor: 'rgba(168, 85, 247, 0.5)',
    shadowBlur: 15,
    shadowOffsetX: 0,
    shadowOffsetY: 0
  },
  minimal: {
    id: 'minimal',
    name: '极简主题',
    backgroundColor: '#fafafa',
    gridColor: '#f5f5f5',
    gridEnabled: false,
    connectionColor: '#d4d4d4',
    lineColor: '#525252',
    connectionWidth: 1,
    connectionStyle: 'straight',
    nodeBackgroundColor: 'transparent',
    nodeBorderColor: '#d4d4d4',
    nodeBorderWidth: 0,
    nodeBorderRadius: 0,
    rootNodeColor: '#ffffffff',
    textColor: '#262626',
    rootTextColor: '#262626',
    fontFamily: 'Helvetica Neue, Arial, sans-serif',
    fontSize: 16,
    rootFontSize: 20,
    lineHeight: 1.3,
    shadowEnabled: false,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0
  },
  warm: {
    id: 'warm',
    name: '暖色主题',
    backgroundColor: '#fefce8',
    gridColor: '#fef08a',
    gridEnabled: true,
    connectionColor: '#ca8a04',
    lineColor: '#ca8a04',
    connectionWidth: 2,
    connectionStyle: 'polyline',
    nodeBackgroundColor: '#fef9c3',
    nodeBorderColor: '#facc15',
    nodeBorderWidth: 2,
    nodeBorderRadius: 16,
    rootNodeColor: '#ffed75ff',
    textColor: '#713f12',
    rootTextColor: '#ffffff',
    fontFamily: 'Comic Sans MS, cursive',
    fontSize: 14,
    rootFontSize: 18,
    lineHeight: 1.6,
    shadowEnabled: true,
    shadowColor: 'rgba(234, 179, 8, 0.3)',
    shadowBlur: 4,
    shadowOffsetX: 2,
    shadowOffsetY: 2
  },
  business: {
    id: 'business',
    name: '商务蓝',
    backgroundColor: '#f8f9fa',
    gridColor: '#e9ecef',
    gridEnabled: true,
    connectionColor: '#adb5bd',
    lineColor: '#0d6efd',
    connectionWidth: 2,
    connectionStyle: 'curve',
    nodeBackgroundColor: '#ffffff',
    nodeBorderColor: '#dee2e6',
    nodeBorderWidth: 1,
    nodeBorderRadius: 4,
    rootNodeColor: '#0d6efd',
    textColor: '#212529',
    rootTextColor: '#ffffff',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    fontSize: 14,
    rootFontSize: 16,
    lineHeight: 1.5,
    shadowEnabled: true,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 4
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: '赛博朋克',
    backgroundColor: '#000000',
    gridColor: '#333333',
    gridEnabled: true,
    connectionColor: '#00ff00',
    lineColor: '#00ff00',
    connectionWidth: 2,
    connectionStyle: 'polyline',
    nodeBackgroundColor: '#111111',
    nodeBorderColor: '#00ff00',
    nodeBorderWidth: 1,
    nodeBorderRadius: 0,
    rootNodeColor: '#04ff00ff',
    textColor: '#00ff00',
    rootTextColor: '#ffffff',
    fontFamily: '"Courier New", Courier, monospace',
    fontSize: 14,
    rootFontSize: 16,
    lineHeight: 1.4,
    shadowEnabled: true,
    shadowColor: 'rgba(0, 255, 0, 0.4)',
    shadowBlur: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 0
  },
  blueprint: {
    id: 'blueprint',
    name: '工程蓝图',
    backgroundColor: '#1e3a8a',
    gridColor: 'rgba(255, 255, 255, 0.1)',
    gridEnabled: true,
    connectionColor: '#ffffff',
    lineColor: '#60a5fa',
    connectionWidth: 1.5,
    connectionStyle: 'straight',
    nodeBackgroundColor: '#1e3a8a',
    nodeBorderColor: '#ffffff',
    nodeBorderWidth: 2,
    nodeBorderRadius: 2,
    rootNodeColor: '#60a5fa',
    textColor: '#ffffff',
    rootTextColor: '#ffffff',
    fontFamily: 'monospace',
    fontSize: 14,
    rootFontSize: 18,
    lineHeight: 1.5,
    shadowEnabled: false,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0
  },
  coffee: {
    id: 'coffee',
    name: '咖啡时光',
    backgroundColor: '#f5ebe0',
    gridColor: '#e3d5ca',
    gridEnabled: false,
    connectionColor: '#d5bdaf',
    lineColor: '#b08968',
    connectionWidth: 2,
    connectionStyle: 'curve',
    nodeBackgroundColor: '#ffffff',
    nodeBorderColor: '#d6ccc2',
    nodeBorderWidth: 1,
    nodeBorderRadius: 12,
    rootNodeColor: '#edc4b3',
    textColor: '#634832',
    rootTextColor: '#5e503f',
    fontFamily: 'Georgia, serif',
    fontSize: 15,
    rootFontSize: 18,
    lineHeight: 1.6,
    shadowEnabled: true,
    shadowColor: 'rgba(99, 72, 50, 0.1)',
    shadowBlur: 6,
    shadowOffsetX: 3,
    shadowOffsetY: 3
  }
};

// 获取默认主题配置
export function getDefaultTheme(): ThemeConfig {
  return { ...presetThemes.default };
}
